### ISSUE TITLE
Consider saving tutorials as ipynb files for easier reproducibility

### ISSUE THREAD

**Issue by seandavi** [perrin-isir/xomx#1]
GitHub can display ipynb files as well as md files. It might be useful to supply the ipynb files so that those who want to follow along with the tutorials can do so more easily. Just a suggestion, though. These look great!

**Comment by perrin-isir** [comment]
Thanks for the comment! I've added an ipynb shorter version of the first tutorial: [xomx_kidney_classif.ipynb](https://github.com/perrin-isir/xomx/blob/master/xomx/tutorials/xomx_kidney_classif.ipynb).
**However, for the moment, the interactive outputs do not work in notebooks**, even with ipympl. This prevents, for example, from hovering over points to get information about samples or features. Therefore, I recommend the "standard" tutorial rather than the notebook. Until the issue is fixed, tutorials as md + py files have the advantage of producing the expected interactive outputs.

**Comment by perrin-isir** [comment]
Hi Sean,
I finally made some big changes in the plotting functions. They can now rely on bokeh to produces Javascript-powered interactive plots, which is nice in notebooks and especially in Colab notebooks (no delays due to computations on the server-side).
So I turned all the tutorials into Colab notebooks. They can be found there:
https://github.com/perrin-isir/xomx-tutorials/
Best,
Nicolas
